# Generated by Django 5.1.5 on 2025-01-31 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('workout_frequency', models.CharField(choices=[('INICIANTE', 'Iniciante 1 - 2 vezes'), ('INTERMEDIARIO', 'Mediano 2 - 4 Vezes'), ('FREQUENTE', 'Alta 4 - 5 Vezes'), ('MAXIMO', 'Insano 5 - 7 Vezes')], default='INICIANTE', max_length=50)),
                ('goals', models.TextField()),
                ('dietary_restrictions', models.TextField()),
                ('extra_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.userprofile')),
            ],
        ),
    ]
