# Generated by Django 2.2.28 on 2025-07-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='descanso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='repeticoes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='series',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
